### ISSUE TITLE
Need to fix dynamic switch to fullscreen mode

### ISSUE THREAD

**Issue by pavel-kudinov** [raub/node-3d-ready#3]
Need to fix dynamic switch to fullscreen mode:

currently both QML GUI & three.js clouds are disapear when switch to fullscreen ( ctrl+f ) and returns on exit from fullscreen ( ctrl+shift+f ).

**Comment by raub** [comment]
BTW if threejs material for the cloud is not `transparent`, it stays visible... trying to investivage this.

**Comment by raub** [comment]
@pavel-kudinov try [the new release v1.1.0](https://github.com/node-3d/3d-core-raub/releases/tag/v1.1.0), it has both bugfix and launch switches.
