### ISSUE TITLE
switch to fullscreen/borderless mode on second monitor

### ISSUE THREAD

**Issue by pavel-kudinov** [raub/node-3d-ready#4]
- switch to borderless mode on secondary screen - takes window size from primary screen (for example, when secondary screen has 4k resolution and first screen has 2k resolution - borderless window appear on secondary screen but has 2k resolution)

- switch to fullscreen mode on secondary screen - make window fullscreen on primary screen and secondary screen starts to flicker

**Comment by raub** [comment]
https://github.com/node-3d/3d-core-raub/tree/v2.1.2
